# These sponsors support the development of Deep-Live-Cam Chrome Edition

github: []
patreon: # Add your Patreon username
ko_fi: # Add your Ko-fi username
tidelift: # Add your Tidelift subscription details
community_bridge: # Add your Community Bridge project slug
liberapay: # Add your Liberapay username
open_collective: # Add your Open Collective slug
custom: # Add custom funding links
