# These sponsors support the development of Deep-Live-Cam Chrome Edition

github:
  - yjdudeplz-web
patreon: ''
ko_fi: ''
tidelift: ''
community_bridge: ''
liberapay: ''
open_collective: ''
custom:
  - url: 'https://huggingface.co/deep-live-cam'
    description: 'Support on HuggingFace'

